# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build, Test & Deploy to GitHub packages and Maven Central

on:
  push:
    tags: [ '*' ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        gpg-private-key: ${{ secrets.GPG_PRIVATEKEY }} # Value of the GPG private key to import        
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        
    - name: Build with Maven
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: mvn -P ci-cd -B clean install --file pom.xml
      
    - name: Deploy with Maven to GitHub Packages
      env:
        GITHUB_ACTOR: ${{ github.actor }} # GITHUB_TOKEN is the default env for the password 
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password 
      run: |
        mvn -B \
          -DskipTests \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/$GITHUB_REPOSITORY \
          --file pom.xml \
          deploy
          
    - name: Set up maven for OSSRH deployment
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_PASSWORD # env variable for token in deploy
        
    - name: Deploy with Maven to Maven Central
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: |
        mvn -B \
          -DskipTests \
          "-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}" \
          -DaltDeploymentRepository=ossrh::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
          --file pom.xml \
          deploy
          
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/vertx-token-validation*.jar*"
        token: ${{ github.token }} 
        
    - uses: actions/delete-package-versions@v3
      with: 
        package-name: 'uk.co.spudsoft.vertx-token-validation'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true" 
        
    - name: Clean up
      run: |
        rm "${HOME}/.m2/settings.xml"        
